name: GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    #permissions:
    #  contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      #- name: Git submodule update
      #  run: |
      #    git submodule update --init --recursive
      #    git submodule update --remote --merge  
        # git submodule update --init --recursive --remote

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          personal_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          #github_token: ${{ secrets.GITHUB_TOKEN }}
          external_repository: Systemad/systemad.github.io
          publish_branch: main
          publish_dir: ./public